image: gradle:6.9.2-jdk11  # Usa una imagen de Gradle con JDK 11

stages:
  - build
  - test

variables:
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Xms256m -Xmx1024m"

# Cache para mejorar velocidad de builds
cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .gradle/wrapper
    - .gradle/caches
  policy: pull-push

before_script:
  - chmod +x ./gradlew
  - ./gradlew --version

compile:
  stage: build
  script:
    - ./gradlew compileJava --build-cache --stacktrace --info
  artifacts:
    paths:
      - build/classes/
    expire_in: 1 hour
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "main"

test:
  stage: test
  script:
    - ./gradlew test --build-cache --continue --stacktrace
  artifacts:
    when: always
    paths:
      - build/reports/tests/
    reports:
      junit: build/test-results/test/*.xml
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "main"



